// Generated by CoffeeScript 1.6.3
(function() {
  doctype(5);

  html({
    lang: "en",
    'ng-app': '',
    'ng-csp': ''
  }, function() {
    head(function() {
      meta({
        charset: 'utf-8'
      });
      title("NU Solar's ZELDA OS");
      link({
        rel: 'stylesheet',
        href: 'main.css'
      });
      script({
        src: 'jquery-2.0.3.js'
      });
      script({
        src: 'angular.min.js'
      });
      return script({
        src: 'main.js'
      });
    });
    return body(function() {
      return article('.MainTable', {
        'ng-controller': 'MainTable'
      }, function() {
        header('.HeaderRow', function() {
          div('.TextCell.Title.TopLeftCorner', function() {});
          div('.TextCell.Title', {
            colspan: '2'
          }, function() {
            return "Title PLACEHOLDER";
          });
          return div('.TextCell.Title.TopRightCorner', function() {});
        });
        div('.CentralRow', function() {
          section('.LeftPanel', function() {
            div('.Button', {
              'ng-class': "{ButtonOn: signals_btn==Signals.Left}",
              'ng-click': 'Left()'
            }, function() {
              return "LEFT";
            });
            div('.Button', {
              'ng-class': "{ButtonOn: signals_btn==Signals.Hazards}",
              'ng-click': 'Hazards()'
            }, function() {
              return "HAZARDS";
            });
            div('.Button', {
              'ng-class': "{ButtonOn: horn_btn}",
              'ng-mousedown': 'SetHorn(true)',
              'ng-mouseup': 'SetHorn(false)'
            }, function() {
              return "HORN";
            });
            div('.Gap', function() {});
            div('.Button', {
              'ng-class': "{ButtonOn: map_btn}",
              'ng-click': 'Map()'
            }, function() {
              return "MAP";
            });
            return div('.Button', {
              'ng-class': "{ButtonOn: sensors_btn}",
              'ng-click': 'Sensors()'
            }, function() {
              return "SENSORS";
            });
          });
          div('.CenterPanel.ng-cloak', function() {
            section('.MapPanel', {
              'ng-show': 'map_btn'
            }, function() {
              return img('.Map', {
                src: 'map.png'
              }, function() {});
            });
            section('.BatteryBoxPanel', {
              'ng-show': 'sensors_btn'
            }, function() {
              return table('.BatteryBoxTable', function() {
                var battery_cell, i, _i, _results;
                battery_cell = function(num) {
                  return td('#battery_' + String(num) + '.Battery', function() {
                    return String(num);
                  });
                };
                tr(battery_cell(31));
                tr(battery_cell(30));
                _results = [];
                for (i = _i = 29; _i >= 25; i = _i += -1) {
                  _results.push(tr(function() {
                    var j, k, _j, _results1;
                    _results1 = [];
                    for (j = _j = i; _j >= 0; j = _j += -10) {
                      _results1.push((function() {
                        var _k, _len, _ref, _results2;
                        _ref = [j, j - (2 * (j % 5) + 1)];
                        _results2 = [];
                        for (_k = 0, _len = _ref.length; _k < _len; _k++) {
                          k = _ref[_k];
                          _results2.push(battery_cell(k));
                        }
                        return _results2;
                      })());
                    }
                    return _results1;
                  }));
                }
                return _results;
              });
            });
            section('.DrivePanel', {
              'ng-show': 'drive_btn'
            }, function() {
              return div('.Button.MotorToggle', {
                'ng-class': "{MotorToggleOn: motor_btn}",
                'ng-click': 'Motor()'
              }, function() {
                return "MOTOR IS {{ (motor_btn? 'ON': 'OFF') }}";
              });
            });
            return section('.CameraPanel', {
              'ng-show': 'camera_btn'
            }, function() {
              return "CAMERA";
            });
          });
          return section('.RightPanel', function() {
            div('.Button', {
              'ng-class': "{ButtonOn: signals_btn==Signals.Right}",
              'ng-click': 'Right()'
            }, function() {
              return "RIGHT";
            });
            div('.Button', {
              'ng-class': "{ButtonOn: headlights_btn}",
              'ng-click': 'Headlights()'
            }, function() {
              return "HEADLIGHTS";
            });
            div('.Button', {
              'ng-class': "{ButtonOn: reverse_btn}",
              'ng-click': 'Reverse()'
            }, function() {
              return "REVERSE";
            });
            div('.Gap', function() {});
            div('.Button', {
              'ng-class': "{ButtonOn: drive_btn}",
              'ng-click': 'Drive()'
            }, function() {
              return "DRIVE";
            });
            return div('.Button', {
              'ng-class': "{ButtonOn: camera_btn}",
              'ng-click': 'Camera()'
            }, function() {
              return "CAMERA";
            });
          });
        });
        return footer('.FooterRow', {
          colspan: '2'
        }, function() {
          div('.TextCell.Bottom.BottomLeftCorner', function() {});
          div('.TextCell.Bottom', {
            colspan: '2',
            'ng-bind': 'query_string'
          }, function() {});
          return div('.TextCell.Bottom.BottomRightCorner', function() {});
        });
      });
    });
  });

}).call(this);
