// Generated by CoffeeScript 1.6.3
(function() {
  var namespace,
    __slice = [].slice;

  namespace = function(target, name, block) {
    var item, top, _i, _len, _ref, _ref1;
    if (arguments.length < 3) {
      _ref = [(typeof exports !== 'undefined' ? exports : window)].concat(__slice.call(arguments)), target = _ref[0], name = _ref[1], block = _ref[2];
    }
    top = target;
    _ref1 = name.split('.');
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      item = _ref1[_i];
      target = target[item] || (target[item] = {});
    }
    return block(target, top);
  };

  window.MainTable = function($scope, $timeout) {
    var timer_id,
      _this = this;
    $scope.left_btn = false;
    $scope.right_btn = false;
    $scope.hazards_btn = false;
    $scope.headlights_btn = false;
    $scope.horn_btn = false;
    $scope.motor_btn = false;
    $scope.commands = {
      drive: 0,
      horn: 0,
      signals: 0,
      headlights: 0
    };
    $scope.set_panel_button = function(panel) {
      var _this = this;
      $scope.map_btn = false;
      $scope.sensors_btn = false;
      $scope.drive_btn = false;
      $scope.camera_btn = false;
      if (panel) {
        return $timeout((function() {
          $scope.current_panel = panel;
          return $scope[$scope.current_panel] = true;
        }), 1);
      }
    };
    $scope.set_panel_button('sensors_btn');
    $scope.Left = function() {
      $scope.hazards_btn = false;
      $scope.right_btn = false;
      $scope.left_btn = !$scope.left_btn;
      return $scope.commands.signals = $scope.left_btn ? 1 : 0;
    };
    $scope.Right = function() {
      $scope.hazards_btn = false;
      $scope.left_btn = false;
      $scope.right_btn = !$scope.right_btn;
      return $scope.commands.signals = $scope.right_btn ? 2 : 0;
    };
    $scope.Hazards = function() {
      $scope.left_btn = false;
      $scope.right_btn = false;
      $scope.hazards_btn = !$scope.hazards_btn;
      return $scope.commands.signals = $scope.hazards_btn ? 3 : 0;
    };
    $scope.Headlights = function() {
      $scope.headlights_btn = !$scope.headlights_btn;
      return $scope.commands.headlights = $scope.headlights_btn ? 1 : 0;
    };
    $scope.SetHorn = function(horn_bool) {
      $scope.horn_btn = horn_bool;
      return $scope.commands.horn = horn_bool ? 1 : 0;
    };
    $scope.Map = function() {
      return $scope.set_panel_button('map_btn');
    };
    $scope.Sensors = function() {
      return $scope.set_panel_button('sensors_btn');
    };
    $scope.Drive = function() {
      return $scope.set_panel_button('drive_btn');
    };
    $scope.Camera = function() {
      return $scope.set_panel_button('camera_btn');
    };
    $scope.Motor = function() {
      $scope.motor_btn = !$scope.motor_btn;
      return $scope.commands.drive = $scope.motor_btn ? 1 : 0;
    };
    return timer_id = setInterval((function() {
      return $scope.$apply(function() {
        $scope.query_string = $.param($scope.commands);
        return $.ajax({
          url: 'http://localhost:8080/data.json',
          dataType: 'jsonp',
          data: $scope.commands,
          success: function(json) {
            return $scope.commands;
          }
        });
      });
    }), 50);
  };

}).call(this);
