// Generated by CoffeeScript 1.6.3
(function() {
  doctype(5);

  html(function() {
    head(function() {
      meta({
        charset: 'utf-8'
      });
      title("NU Solar's ZELDA OS");
      link({
        rel: 'stylesheet',
        href: 'main.css'
      });
      script({
        src: 'jquery-2.0.3.js'
      });
      script({
        src: 'agility.min.js'
      });
      return script({
        src: 'main.js'
      });
    });
    return body('#body', function() {
      header('.HeaderBar', function() {
        return "Title PLACEHOLDER";
      });
      article('.CentralRowWrapper', function() {});
      footer('.FooterBar', function() {
        return "no content";
      });
      return div('#templates', function() {
        script('#button_template', {
          type: 'text/html'
        }, function() {
          return div('.Button', {
            data: {
              bind: 'text'
            }
          }, function() {});
        });
        script('#left_template', {
          type: 'text/html'
        }, function() {
          return section('.LeftPanel', function() {});
        });
        script('#right_template', {
          type: 'text/html'
        }, function() {
          return section('.RightPanel', function() {});
        });
        script('#battery_box_template', {
          type: 'text/html'
        }, function() {
          return section('.BatteryBoxPanel', function() {
            return table('.BatteryBoxTable', function() {
              var battery_cell, i, _i, _results;
              battery_cell = function(num) {
                return td('#battery_' + String(num) + '.Battery', function() {
                  return String(num);
                });
              };
              tr(battery_cell(31));
              tr(battery_cell(30));
              _results = [];
              for (i = _i = 29; _i >= 25; i = _i += -1) {
                _results.push(tr(function() {
                  var j, k, _j, _results1;
                  _results1 = [];
                  for (j = _j = i; _j >= 0; j = _j += -10) {
                    _results1.push((function() {
                      var _k, _len, _ref, _results2;
                      _ref = [j, j - (2 * (j % 5) + 1)];
                      _results2 = [];
                      for (_k = 0, _len = _ref.length; _k < _len; _k++) {
                        k = _ref[_k];
                        _results2.push(battery_cell(k));
                      }
                      return _results2;
                    })());
                  }
                  return _results1;
                }));
              }
              return _results;
            });
          });
        });
        script('#map_template', {
          type: 'text/html'
        }, function() {
          return section('.MapPanel', function() {
            return "MAP";
          });
        });
        script('#drive_template', {
          type: 'text/html'
        }, function() {
          return section('.DrivePanel', function() {
            return "DRIVE";
          });
        });
        script('#camera_template', {
          type: 'text/html'
        }, function() {
          return section('.CameraPanel', function() {
            return "CAMERA";
          });
        });
        script('#central_template', {
          type: 'text/html'
        }, function() {
          return div('.CenterPanel', function() {});
        });
        return script('#central_row_template', {
          type: 'text/html'
        }, function() {
          return div('.CentralRow', function() {});
        });
      });
    });
  });

}).call(this);
