// Generated by CoffeeScript 1.6.3
(function() {
  var BatteryBox, Button, Camera, Drive, MainTable, Map, Toggle, namespace,
    __slice = [].slice,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  namespace = function(target, name, block) {
    var item, top, _i, _len, _ref, _ref1;
    if (arguments.length < 3) {
      _ref = [(typeof exports !== 'undefined' ? exports : window)].concat(__slice.call(arguments)), target = _ref[0], name = _ref[1], block = _ref[2];
    }
    top = target;
    _ref1 = name.split('.');
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      item = _ref1[_i];
      target = target[item] || (target[item] = {});
    }
    return block(target, top);
  };

  namespace('Model', function(exports) {
    var k, v, _ref, _results;
    exports.serial_devices = {
      horn: "/dev/ttyACM.horn",
      left: "/dev/ttyACM.left",
      right: "/dev/ttyACM.right",
      headlights: "/dev/ttyACM.headlights",
      brakelights: "/dev/ttyACM.brakelights"
    };
    exports.UsbSerial = (function() {
      UsbSerial.prototype._value = 0;

      UsbSerial.prototype.value = function() {
        return _value;
      };

      UsbSerial.prototype.ab2str = function(buff) {
        return String.fromCharCode.apply(null, new UInt8Array(buff));
      };

      UsbSerial.prototype.str2ab = function(str) {
        var buf, bufView, i, _i, _ref, _results;
        buf = new ArrayBuffer(str.length);
        bufView = new UInt8Array(buf);
        _results = [];
        for (i = _i = 0, _ref = str.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
          _results.push(bufView[i] = str.charCodeAt(i));
        }
        return _results;
      };

      UsbSerial.prototype.write = function(str, call) {
        if (call == null) {
          call = function() {};
        }
        return chrome.serial.write(this.connection_id, str2ab(str), call);
      };

      UsbSerial.prototype.off = function() {
        return this.write("off", function() {
          var _value;
          return _value = 0;
        });
      };

      UsbSerial.prototype.on = function() {
        return this.write("on", function() {
          var _value;
          return _value = 1;
        });
      };

      UsbSerial.prototype.toggle = function() {
        var _value;
        return _value = !_value;
      };

      function UsbSerial(name) {
        this.name = name;
        chrome.serial.open(this.name, {
          bitrate: 115200
        }, function(connection_info) {
          this.connection_id = connection_info.connectionId;
          return console.log("Serial port opened: " + this.name);
        });
      }

      UsbSerial.prototype.destroy = function() {
        return chrome.serial.close(this.connection_id, function() {
          return console.log("Serial port closed: " + this.name);
        });
      };

      return UsbSerial;

    })();
    exports.usb = new Object();
    _ref = exports.serial_devices;
    _results = [];
    for (k in _ref) {
      v = _ref[k];
      _results.push(exports.usb[k] = new exports.UsbSerial(v));
    }
    return _results;
  });

  /*
  NOTE: Sub-class methods of Classes that extend/become MVC objects are always
  	executed in the scope of the MVC class (e.g. Button), NOT the subclasses
  	(e.g. model, view, or controller)
  */


  Button = (function(_super) {
    __extends(Button, _super);

    Button.Controller = (function() {
      function Controller(click) {
        this.click = click;
      }

      Controller.prototype['mousedown &'] = function() {
        this.view.$().css('background-color', 'blue');
        return this.controller.click(true);
      };

      Controller.prototype['mouseup &'] = function() {
        this.view.$().css('background-color', '');
        return this.controller.click(false);
      };

      Controller.prototype['mouseout &'] = function() {
        return this.controller['mouseup &']();
      };

      return Controller;

    })();

    function Button(title, click) {
      var model, view;
      if (click == null) {
        click = function() {
          return true;
        };
      }
      model = {
        text: title
      };
      view = $('#button_template').html();
      return $$(model, view, new Button.Controller(click));
    }

    return Button;

  })($$);

  Toggle = (function() {
    Toggle.prototype.mousedown = false;

    Toggle.prototype.controller = {
      'change': function() {
        return this.view.$().css({
          'background-color': this.model.get('state') ? '#FFFF33' : ''
        });
      },
      'mousedown &': function() {
        return this.mousedown = true;
      },
      'mouseup &': function() {
        if (this.mousedown) {
          this.mousedown = false;
          return this.toggle(this.model.set({
            'state': !this.model.get('state')
          }));
        }
      },
      'mouseout &': function() {
        return this.mousedown = false;
      },
      'create': function() {
        return this.model.set({
          'state': this.model.get('state')
        });
      }
    };

    function Toggle(title, initial, toggle) {
      if (initial == null) {
        initial = false;
      }
      this.toggle = toggle != null ? toggle : function() {};
      this.view = {
        format: $('#button_template').html()
      };
      this.model = {
        state: initial,
        text: title
      };
    }

    return Toggle;

  })();

  BatteryBox = (function(_super) {
    __extends(BatteryBox, _super);

    BatteryBox.Controller = (function() {
      function Controller() {}

      Controller.prototype['create'] = function() {};

      return Controller;

    })();

    function BatteryBox() {
      var view;
      view = $('#battery_box_template').html();
      return $$({}, view, new BatteryBox.Controller());
    }

    return BatteryBox;

  })($$);

  Map = (function(_super) {
    __extends(Map, _super);

    Map.Controller = (function() {
      function Controller() {}

      Controller.prototype['create'] = function() {};

      return Controller;

    })();

    function Map() {
      var view;
      view = $('#map_template').html();
      return $$({}, view, new Map.Controller());
    }

    return Map;

  })($$);

  Drive = (function(_super) {
    __extends(Drive, _super);

    Drive.Controller = (function() {
      function Controller() {}

      Controller.prototype['create'] = function() {
        this.append(this.start = $$(new Toggle("START")));
        return this.start.view.$().css({
          'max-width': '20%'
        });
      };

      Controller.prototype['child:change:state'] = function(e) {
        return console.log(this.start.model.get('state'));
      };

      return Controller;

    })();

    function Drive() {
      var view;
      view = $('#drive_template').html();
      return $$({}, view, new Drive.Controller());
    }

    return Drive;

  })($$);

  Camera = (function(_super) {
    __extends(Camera, _super);

    Camera.Controller = (function() {
      function Controller() {}

      Controller.prototype['create'] = function() {};

      return Controller;

    })();

    function Camera() {
      var view;
      view = $('#camera_template').html();
      return $$({}, view, new Camera.Controller());
    }

    return Camera;

  })($$);

  MainTable = (function(_super) {
    __extends(MainTable, _super);

    MainTable.Controller = (function() {
      function Controller() {}

      Controller.prototype.panels = {};

      Controller.prototype._current_panel = null;

      Controller.prototype.show = function(state, panel) {
        var _this = this;
        if (state) {
          this.controller._current_panel.view.$().css('display', 'none');
          this.controller._current_panel = this.controller.panels[panel];
          return window.setTimeout((function() {
            return _this.controller._current_panel.view.$().css('display', 'block');
          }), 0);
        }
      };

      Controller.prototype['create'] = function() {
        var _this = this;
        this.append(this.controller.panels['map'] = new Map(), '.CenterPanel');
        this.append(this.controller.panels['sensors'] = new BatteryBox(), '.CenterPanel');
        this.append(this.controller.panels['drive'] = new Drive(), '.CenterPanel');
        this.append(this.controller.panels['camera'] = new Camera(), '.CenterPanel');
        this.controller._current_panel = this.controller.panels['sensors'];
        this.append(this.left = new Button("LEFT"), '.LeftPanel');
        this.append(this.haz = new Button("HAZARDS"), '.LeftPanel');
        this.append(this.rev = new Button("REVERSE"), '.LeftPanel');
        this.append(this.map = new Button("MAP", function(s) {
          return _this.controller.show(s, 'map');
        }), '.LeftPanel');
        this.append(this.sens = new Button("SENSORS", function(s) {
          return _this.controller.show(s, 'sensors');
        }), '.LeftPanel');
        this.append(this.right = new Button("RIGHT"), '.RightPanel');
        this.append(this.heads = new Button("HEADLIGHTS"), '.RightPanel');
        this.append(this.horn = new Button("HORN"), '.RightPanel');
        this.append(this.drive = new Button("DRIVE", function(s) {
          return _this.controller.show(s, 'drive');
        }), '.RightPanel');
        return this.append(this.cam = new Button("CAMERA", function(s) {
          return _this.controller.show(s, 'camera');
        }), '.RightPanel');
      };

      return Controller;

    })();

    function MainTable() {
      var view;
      view = $('#main_table_template').html();
      return $$({}, view, new MainTable.Controller());
    }

    return MainTable;

  })($$);

  $(function() {
    window.mouse_down = false;
    document.body.onmouseup = function(e) {
      if (e.button === 0) {
        return window.mouse_down = false;
      }
    };
    document.body.onmousedown = function(e) {
      if (e.button === 0) {
        return window.mouse_down = true;
      }
    };
    return $$.document.append(new MainTable());
  });

}).call(this);
