// Generated by CoffeeScript 1.6.3
(function() {
  var namespace,
    __slice = [].slice;

  namespace = function(target, name, block) {
    var item, top, _i, _len, _ref, _ref1;
    if (arguments.length < 3) {
      _ref = [(typeof exports !== 'undefined' ? exports : window)].concat(__slice.call(arguments)), target = _ref[0], name = _ref[1], block = _ref[2];
    }
    top = target;
    _ref1 = name.split('.');
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      item = _ref1[_i];
      target = target[item] || (target[item] = {});
    }
    return block(target, top);
  };

  window.MainTable = function($scope, $timeout) {
    $scope.left_btn = false;
    $scope.right_btn = false;
    $scope.hazards_btn = false;
    $scope.headlights_btn = false;
    $scope.horn_btn = false;
    $scope.motor_btn = false;
    $scope.motor_state = ["OFF", "ON"];
    $scope.set_panel_button = function(panel) {
      var _this = this;
      $scope.map_btn = false;
      $scope.sensors_btn = false;
      $scope.drive_btn = false;
      $scope.camera_btn = false;
      if (panel) {
        return $timeout((function() {
          $scope.current_panel = panel;
          return $scope[$scope.current_panel] = true;
        }), 0);
      }
    };
    $scope.set_panel_button('sensors_btn');
    $scope.Left = function() {
      $scope.hazards_btn = false;
      $scope.right_btn = false;
      return $scope.left_btn = !$scope.left_btn;
    };
    $scope.Right = function() {
      $scope.hazards_btn = false;
      $scope.left_btn = false;
      return $scope.right_btn = !$scope.right_btn;
    };
    $scope.Hazards = function() {
      $scope.left_btn = false;
      $scope.right_btn = false;
      return $scope.hazards_btn = !$scope.hazards_btn;
    };
    $scope.Headlights = function() {
      return $scope.headlights_btn = !$scope.headlights_btn;
    };
    $scope.SetHorn = function(horn_bool) {
      return $scope.horn_btn = horn_bool;
    };
    $scope.Map = function() {
      return $scope.set_panel_button('map_btn');
    };
    $scope.Sensors = function() {
      return $scope.set_panel_button('sensors_btn');
    };
    $scope.Drive = function() {
      return $scope.set_panel_button('drive_btn');
    };
    $scope.Camera = function() {
      return $scope.set_panel_button('camera_btn');
    };
    return $scope.Motor = function() {
      return $scope.motor_btn = !$scope.motor_btn;
    };
  };

}).call(this);
